services:
  # Сервис базы данных
  db:
    image: postgres:16-alpine
    container_name: fastshop_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Панель управления БД
  pgadmin:
    image: dpage/pgadmin4
    container_name: fastshop_pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy

  # Основное приложение
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: fastapi_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/backend:/app/backend
      - ./src/alembic:/app/alembic
      - ./src/alembic.ini:/app/alembic.ini
    networks:
      - backend_network

  # Фронтенд заглушка (Nginx)
  frontend:
    image: nginx:alpine
    container_name: fastshop_frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: